<?php

namespace ContainerBR1NdBl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XSL6eaBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xSL6eaB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xSL6eaB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'appointment' => ['privates', '.errored..service_locator.xSL6eaB.App\\Entity\\Appointment', NULL, 'Cannot autowire service ".service_locator.xSL6eaB": it needs an instance of "App\\Entity\\Appointment" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'appointment' => 'App\\Entity\\Appointment',
            'entityManager' => '?',
        ]);
    }
}
