<?php

namespace ContainerBR1NdBl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.84yzHQ8.App\Controller\AdminController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.84yzHQ8.App\\Controller\\AdminController::show()'] = ($container->privates['.service_locator.84yzHQ8'] ?? $container->load('get_ServiceLocator_84yzHQ8Service'))->withContext('App\\Controller\\AdminController::show()', $container);
    }
}
