<?php

namespace ContainerBR1NdBl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerhealthLogDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0UDK4ie.App\Controller\AdminController::healthLogDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0UDK4ie.App\\Controller\\AdminController::healthLogDelete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'healthLogRepository' => ['privates', 'App\\Repository\\HealthLogRepository', 'getHealthLogRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'healthLogRepository' => 'App\\Repository\\HealthLogRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\AdminController::healthLogDelete()', $container);
    }
}
