<?php

namespace ContainerBR1NdBl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerhealthStatsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dDsnmDL.App\Controller\AdminController::healthStats()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dDsnmDL.App\\Controller\\AdminController::healthStats()'] = ($container->privates['.service_locator.dDsnmDL'] ?? $container->load('get_ServiceLocator_DDsnmDLService'))->withContext('App\\Controller\\AdminController::healthStats()', $container);
    }
}
