<?php

namespace ContainerBR1NdBl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllereditCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fZFweOq.App\Controller\BlogController::editComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fZFweOq.App\\Controller\\BlogController::editComment()'] = ($container->privates['.service_locator.fZFweOq'] ?? $container->load('get_ServiceLocator_FZFweOqService'))->withContext('App\\Controller\\BlogController::editComment()', $container);
    }
}
