<?php

namespace ContainerBR1NdBl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControlleruserDashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0YiphU7.App\Controller\DashboardController::userDashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0YiphU7.App\\Controller\\DashboardController::userDashboard()'] = ($container->privates['.service_locator.0YiphU7'] ?? $container->load('get_ServiceLocator_0YiphU7Service'))->withContext('App\\Controller\\DashboardController::userDashboard()', $container);
    }
}
