<?php

namespace ContainerBR1NdBl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControlleradminDashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TyVpmiW.App\Controller\DashboardController::adminDashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TyVpmiW.App\\Controller\\DashboardController::adminDashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'doctorRepository' => ['privates', 'App\\Repository\\DoctorRepository', 'getDoctorRepositoryService', true],
            'adminRepository' => ['privates', 'App\\Repository\\AdminRepository', 'getAdminRepositoryService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'doctorRepository' => 'App\\Repository\\DoctorRepository',
            'adminRepository' => 'App\\Repository\\AdminRepository',
        ]))->withContext('App\\Controller\\DashboardController::adminDashboard()', $container);
    }
}
