<?php

namespace ContainerBR1NdBl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctorControllerdeactivateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KvLd2wa.App\Controller\DoctorController::deactivate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KvLd2wa.App\\Controller\\DoctorController::deactivate()'] = ($container->privates['.service_locator.KvLd2wa'] ?? $container->load('get_ServiceLocator_KvLd2waService'))->withContext('App\\Controller\\DoctorController::deactivate()', $container);
    }
}
