<?php

namespace ContainerBR1NdBl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingControllerdoctorsListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._aI6t5A.App\Controller\RatingController::doctorsList()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._aI6t5A.App\\Controller\\RatingController::doctorsList()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctorRepository' => ['privates', 'App\\Repository\\DoctorRepository', 'getDoctorRepositoryService', true],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'doctorRepository' => 'App\\Repository\\DoctorRepository',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]))->withContext('App\\Controller\\RatingController::doctorsList()', $container);
    }
}
