<?php

namespace ContainerBR1NdBl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4VCqJOp.App\Controller\UserController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4VCqJOp.App\\Controller\\UserController::new()'] = ($container->privates['.service_locator.4VCqJOp'] ?? $container->load('get_ServiceLocator_4VCqJOpService'))->withContext('App\\Controller\\UserController::new()', $container);
    }
}
