<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBR1NdBl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBR1NdBl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBR1NdBl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBR1NdBl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBR1NdBl\App_KernelDevDebugContainer([
    'container.build_hash' => 'BR1NdBl',
    'container.build_id' => '8049b853',
    'container.build_time' => 1771925610,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBR1NdBl');
