<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentControllerconfirmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y8zRTA5.App\Controller\AppointmentController::confirm()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y8zRTA5.App\\Controller\\AppointmentController::confirm()'] = ($container->privates['.service_locator.y8zRTA5'] ?? $container->load('get_ServiceLocator_Y8zRTA5Service'))->withContext('App\\Controller\\AppointmentController::confirm()', $container);
    }
}
