<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentControllergenerateInvoiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GsvqroW.App\Controller\AppointmentController::generateInvoice()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GsvqroW.App\\Controller\\AppointmentController::generateInvoice()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'appointment' => ['privates', '.errored..service_locator.GsvqroW.App\\Entity\\Appointment', NULL, 'Cannot autowire service ".service_locator.GsvqroW": it needs an instance of "App\\Entity\\Appointment" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'appointment' => 'App\\Entity\\Appointment',
        ]))->withContext('App\\Controller\\AppointmentController::generateInvoice()', $container);
    }
}
