<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentControllercancelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xSL6eaB.App\Controller\AppointmentController::cancel()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xSL6eaB.App\\Controller\\AppointmentController::cancel()'] = ($container->privates['.service_locator.xSL6eaB'] ?? $container->load('get_ServiceLocator_XSL6eaBService'))->withContext('App\\Controller\\AppointmentController::cancel()', $container);
    }
}
