<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerregisterPatientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.61QrX3A.App\Controller\AuthController::registerPatient()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.61QrX3A.App\\Controller\\AuthController::registerPatient()'] = ($container->privates['.service_locator.61QrX3A'] ?? $container->load('get_ServiceLocator_61QrX3AService'))->withContext('App\\Controller\\AuthController::registerPatient()', $container);
    }
}
