<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentControllersuggestAppointmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tyCNSRE.App\Controller\AppointmentController::suggestAppointment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tyCNSRE.App\\Controller\\AppointmentController::suggestAppointment()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trackingRepository' => ['privates', 'App\\Repository\\DailyTrackingRepository', 'getDailyTrackingRepositoryService', true],
        ], [
            'trackingRepository' => 'App\\Repository\\DailyTrackingRepository',
        ]))->withContext('App\\Controller\\AppointmentController::suggestAppointment()', $container);
    }
}
