<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentMailerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AppointmentMailer' shared autowired service.
     *
     * @return \App\Service\AppointmentMailer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\AppointmentMailer": argument "$mailer" of method "__construct()" has type "Symfony\\Component\\Mailer\\MailerInterface" but this class was not found.');
    }
}
