<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.95Jehk..App\Controller\BlogController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.95Jehk..App\\Controller\\BlogController::edit()'] = ($container->privates['.service_locator.95Jehk.'] ?? $container->load('get_ServiceLocator_95Jehk_Service'))->withContext('App\\Controller\\BlogController::edit()', $container);
    }
}
