<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctorControlleractivateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KvLd2wa.App\Controller\DoctorController::activate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KvLd2wa.App\\Controller\\DoctorController::activate()'] = ($container->privates['.service_locator.KvLd2wa'] ?? $container->load('get_ServiceLocator_KvLd2waService'))->withContext('App\\Controller\\DoctorController::activate()', $container);
    }
}
