<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctorControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BnC8870.App\Controller\DoctorController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BnC8870.App\\Controller\\DoctorController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctorRepository' => ['privates', 'App\\Repository\\DoctorRepository', 'getDoctorRepositoryService', true],
        ], [
            'doctorRepository' => 'App\\Repository\\DoctorRepository',
        ]))->withContext('App\\Controller\\DoctorController::index()', $container);
    }
}
