<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctor3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oUxZNUL.App\Entity\Doctor' shared service.
     *
     * @return \App\Entity\Doctor
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oUxZNUL": it needs an instance of "App\\Entity\\Doctor" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
