<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctorControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sEQP2tc.App\Controller\DoctorController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sEQP2tc.App\\Controller\\DoctorController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctor' => ['privates', '.errored..service_locator.sEQP2tc.App\\Entity\\Doctor', NULL, 'Cannot autowire service ".service_locator.sEQP2tc": it needs an instance of "App\\Entity\\Doctor" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'doctor' => 'App\\Entity\\Doctor',
        ]))->withContext('App\\Controller\\DoctorController::show()', $container);
    }
}
