<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctorControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oUxZNUL.App\Controller\DoctorController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oUxZNUL.App\\Controller\\DoctorController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctor' => ['privates', '.errored..service_locator.oUxZNUL.App\\Entity\\Doctor', NULL, 'Cannot autowire service ".service_locator.oUxZNUL": it needs an instance of "App\\Entity\\Doctor" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'doctor' => 'App\\Entity\\Doctor',
            'entityManager' => '?',
            'passwordHasher' => '?',
            'tokenStorage' => '?',
        ]))->withContext('App\\Controller\\DoctorController::edit()', $container);
    }
}
