<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerdoctorDashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S6yUaer.App\Controller\DashboardController::doctorDashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S6yUaer.App\\Controller\\DashboardController::doctorDashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
            'appointmentRepository' => ['privates', 'App\\Repository\\AppointmentRepository', 'getAppointmentRepositoryService', true],
        ], [
            'ratingRepository' => 'App\\Repository\\RatingRepository',
            'appointmentRepository' => 'App\\Repository\\AppointmentRepository',
        ]))->withContext('App\\Controller\\DashboardController::doctorDashboard()', $container);
    }
}
