<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParapharmacieControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.70vVoeX.App\Controller\ParapharmacieController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.70vVoeX.App\\Controller\\ParapharmacieController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'parapharmacieRepository' => ['privates', 'App\\Repository\\ParapharmacieRepository', 'getParapharmacieRepositoryService', true],
        ], [
            'parapharmacieRepository' => 'App\\Repository\\ParapharmacieRepository',
        ]))->withContext('App\\Controller\\ParapharmacieController::index()', $container);
    }
}
