<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingControllerrateDoctorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hF2Yq8U.App\Controller\RatingController::rateDoctor()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hF2Yq8U.App\\Controller\\RatingController::rateDoctor()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctor' => ['privates', '.errored..service_locator.hF2Yq8U.App\\Entity\\Doctor', NULL, 'Cannot autowire service ".service_locator.hF2Yq8U": it needs an instance of "App\\Entity\\Doctor" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'doctor' => 'App\\Entity\\Doctor',
            'entityManager' => '?',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]))->withContext('App\\Controller\\RatingController::rateDoctor()', $container);
    }
}
