<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackingControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2st3JUr.App\Controller\TrackingController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2st3JUr.App\\Controller\\TrackingController::index()'] = ($container->privates['.service_locator.2st3JUr'] ?? $container->load('get_ServiceLocator_2st3JUrService'))->withContext('App\\Controller\\TrackingController::index()', $container);
    }
}
