<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWishlistControllerremoveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aaZD7Jk.App\Controller\WishlistController::remove()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aaZD7Jk.App\\Controller\\WishlistController::remove()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'wishlistRepository' => ['privates', 'App\\Repository\\WishlistRepository', 'getWishlistRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'wishlistRepository' => 'App\\Repository\\WishlistRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\WishlistController::remove()', $container);
    }
}
