<?php

namespace ContainerMW5XKLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWishlistControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.esw6jeS.App\Controller\WishlistController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.esw6jeS.App\\Controller\\WishlistController::add()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepository' => ['privates', 'App\\Repository\\ParapharmacieRepository', 'getParapharmacieRepositoryService', true],
            'wishlistRepository' => ['privates', 'App\\Repository\\WishlistRepository', 'getWishlistRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'productRepository' => 'App\\Repository\\ParapharmacieRepository',
            'wishlistRepository' => 'App\\Repository\\WishlistRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\WishlistController::add()', $container);
    }
}
