<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Appointment extends \App\Entity\Appointment implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'appointmentDate' => [parent::class, 'appointmentDate', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'doctorEmail' => [parent::class, 'doctorEmail', null, 16],
        "\0".parent::class."\0".'doctorName' => [parent::class, 'doctorName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'parapharmacies' => [parent::class, 'parapharmacies', null, 16],
        "\0".parent::class."\0".'patientEmail' => [parent::class, 'patientEmail', null, 16],
        "\0".parent::class."\0".'patientName' => [parent::class, 'patientName', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'appointmentDate' => [parent::class, 'appointmentDate', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'doctorEmail' => [parent::class, 'doctorEmail', null, 16],
        'doctorName' => [parent::class, 'doctorName', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'parapharmacies' => [parent::class, 'parapharmacies', null, 16],
        'patientEmail' => [parent::class, 'patientEmail', null, 16],
        'patientName' => [parent::class, 'patientName', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
